export const GET_NEWS = 'GET_NEWS'
export const GET_NEWS_SAGA = 'GET_NEWS_SAGA'

export const GET_NEWS_WITH_SEARCH = 'GET_NEWS_WITH_SEARCH'
export const GET_NEWS_WITH_SEARCH_SAGA = 'GET_NEWS_WITH_SEARCH_SAGA'

export const GET_NEWS_WITH_CATEGORIES = 'GET_NEWS_WITH_CATEGORIES'
export const GET_NEWS_WITH_CATEGORIES_SAGA = 'GET_NEWS_WITH_CATEGORIES_SAGA'

export const SET_LOADING = 'SET_LOADING'

export const SET_COUNTRY = 'SET_COUNTRY'
export const SET_COUNTRY_SAGA = 'SET_COUNTRY_SAGA'

export const SET_COLOR = 'SET_COLOR'
